services:
  mongo:
    container_name: "mongo-db-comparison"
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - "databases"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    restart: on-failure

  cassandra:
    container_name: "cassandra-db-comparison"
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      - "databases"
    restart: on-failure

  postgres:
    container_name: "postgres-db-comparison"
    build: ./postgresConfig
    networks:
      - "databases"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
networks:
  databases: {}
